### ISSUE TITLE
关于hue的问题

### ISSUE THREAD

**Issue by fangru07** [iamabug/BigDataParty#1]
![image](https://user-images.githubusercontent.com/49635625/71455282-49e9e400-27cf-11ea-97ae-f6094e39f2b6.png
/usr/ share下面没有hue的目录
hue 会报错 “database is locked”

**Comment by iamabug** [comment]
你是直接运行打好的镜像还是自己构建的？
下面是我运行的截图，是有 hue 目录的：
![](https://tva1.sinaimg.cn/large/006tNbRwly1ga9y60g4myj30v203qt9c.jpg)

**Comment by fangru07** [comment]
> 你是直接运行打好的镜像还是自己构建的？
> 下面是我运行的截图，是有 hue 目录的：
> ![](https://camo.githubusercontent.com/4432cc9c38b7f20b911a83a59b5fdac03ad10f5f/68747470733a2f2f747661312e73696e61696d672e636e2f6c617267652f303036744e6252776c793167613979363067346d796a333076323033717439632e6a7067)
sorry，是我自己的问题，好像是因为hdfs权限的问题，

**Comment by iamabug** [comment]
ok
