### ISSUE TITLE
可以再准备一份centos7的镜像吗？

### ISSUE THREAD

**Issue by henry286700143** [iamabug/BigDataParty#2]
您好，因为平时都用的centos系列的系统，可以做一份基于centos7的镜像吗。。。

**Comment by iamabug** [comment]
感谢关注。

的确不同发行版的linux使用起来会有所差异，但是我需要确认一下是否有必要，因为就我的使用来说，我一般会使用hdfs的上传，kafka的生产消费，spark和flink任务的提交，这些功能本身是跨发行版的（即命令在centos和ubuntu上都是一样的），所以想知道你是哪里使用不便。

另外，这个镜像是基于 hue 的官方镜像构建的，hue的官方镜像是基于ubuntu的，如果要切换成 centos的，hue的集成可能会有点困难。（hue的镜像构建比较复杂。）

**Comment by henry286700143** [comment]
噢噢，好的。只是我平常使用习惯的问题。谢谢回复～～
