### ISSUE TITLE
need solr?

### ISSUE THREAD

**Issue by jinjim** [iamabug/BigDataParty#3]
![image](https://user-images.githubusercontent.com/8455083/75689492-40538f80-5cdc-11ea-89ee-32faaa3c4cbe.png)

**Comment by iamabug** [comment]
Sorry for this late reply, do you mean you need include solr in this image ?

**Comment by jinjim** [comment]
if include would be better,3q

**Comment by iamabug** [comment]
Sorry, I have never used Solr before. You are very welcome to add it by yourself.
