### ISSUE TITLE
pull错误：failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/3649c955a63a89e440376d1fc3ce6a140de26e250aac057977c0e922be385f62/merged: too many levels of symbolic links

### ISSUE THREAD

**Issue by Jack-data-dev** [iamabug/BigDataParty#5]
`docker pull iamabug1128/bdp`
=>
`failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/3649c955a63a89e440376d1fc3ce6a140de26e250aac057977c0e922be385f62/merged: too many levels of symbolic links`

**Comment by iamabug** [comment]
这个问题看起来和镜像本身关系不大，你可以参考一下：
https://stackoverflow.com/questions/60209172/docker-cannot-delete-intermediate-images-from-a-broken-pull
